apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-client
  template:
    metadata:
      labels:
        app: map-client
    spec:
      imagePullSecrets:
        - name: <Your secret>
      containers:
      - name: map-client
        image: <Your image>
        resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/config.json
            subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: map-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: map-client
spec:
  type: LoadBalancer
  selector:
    app: map-client
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: map-client-config
data:
  config.json: |
    {
      "API": "http://127.0.0.1:8080/api/v1/client"
    }
